version: "3.8"
services:
  app:
    build: .
    container_name: app_c
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
